# TODO: check here for more industry standards https://docs.gitlab.com/ee/topics/autodevops/

stages:
    - .pre
    - build
    - test
    - release
    - deploy

image: registry.gitlab.com/<groupname>/cicd

cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
        - node_modules/

pre_install:
    stage: .pre
    script: npm ci
    before_script:
        - eval $(ssh-agent -s)
        - echo "$SSH_GITLAB_KEY" | tr -d '\r' | ssh-add -    

pre_audit:
    stage: .pre
    script: npm run audit

pre_format:
    stage: .pre
    script: npm run format

pre_lint:
    stage: .pre
    script: npm run lint

build_compile:
    stage: build
    script: npm run build

test_unit:
    stage: test
    script: npm test
    artifacts:
        paths:
            - coverage/
        reports:
            junit: junit.xml
            cobertura: coverage/cobertura-coverage.xml

release_version:
    stage: release
    script: npm version prerelease --preid=$(git rev-parse --abbrev-ref HEAD)

deploy_test:
    stage: deploy
    only: develop
    script: npm run deploy:test
    before_script:
        - if [ $CI_PROJECT_NAME == "app" ] ; then expo login --non-interactive -u $EXPO_CLI_USERNAME ; fi

deploy_prod:
    stage: deploy
    only: master
    script: npm run deploy:prod

pages:
    stage: deploy
    only: master
    script:
        - mv coverage/ public/
    artifacts:
        paths:
            - public