stages:
    - .pre
    - build
    - test

image: registry.gitlab.com/aardonyx/base

cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
        - node_modules/

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_GITLAB_KEY" | tr -d '\r' | ssh-add -

install:
    stage: .pre
    script: npm ci

audit:
    stage: .pre
    script: npm run audit

format:
    stage: .pre
    script: npm run format

lint:
    stage: .pre
    script: npm run lint

compile:
    stage: build
    script: npm run build

unit:
    stage: test
    script: npm test
