stages:
    - .pre
    - build
    - test
    - deploy

image: registry.gitlab.com/aardonyx/base

cache:
    untracked: true
    key: "$CI_BUILD_REF_NAME"
    paths:
        - node_modules/

before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_GITLAB_KEY" | tr -d '\r' | ssh-add -

pre_install:
    stage: .pre
    script: npm ci

pre_audit:
    stage: .pre
    script: npm run audit

pre_format:
    stage: .pre
    script: npm run format

pre_lint:
    stage: .pre
    script: npm run lint

build_compile:
    stage: build
    script: npm run build

test_unit:
    stage: test
    script: npm test

deploy_test:
    stage: deploy
    only:
        - develop
    script: npm run deploy:test

deploy_prod:
    stage: deploy
    only:
        - master
    script: npm run deploy:prod
